import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navigation from "@/components/navigation/navigation";
import { ReactQueryClientProvider } from "@/providers/react-query-provider";
import { UserProvider } from "@/providers/user-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
        >
          <ReactQueryClientProvider>
            <UserProvider>
              <div className="dark:bg-gray-900 bg-gray-100 dark:text-gray-100 w-full min-h-screen p-10">
                {children}
              </div>
            </UserProvider>
          </ReactQueryClientProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
