import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import Logo from "@/components/logo/page";
import { UserAvatar } from "@/components/user/user-avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} h-screen flex flex-col`}>
      {/* Fixed Navbar */}
      <nav className="fixed top-0 left-0 right-0 h-16 bg-white shadow z-10 flex justify-between items-center px-4">
        <Logo />
        <div className="flex items-center justify-end gap-5">
          <UserAvatar />
          <Button variant={"secondary"}>
            <Link href={"/sign-out"} prefetch>
              Logout
            </Link>
          </Button>
        </div>
      </nav>

      {/* Main Content Area */}
      <div className="flex flex-1 pt-16">
        {/* Fixed Sidebar */}
        <aside className="fixed top-16 left-0 h-full w-1/4 bg-gray-100 shadow">
          {/* Sidebar content here */}
        </aside>

        {/* Page Content */}
        <main className="ml-1/4 w-3/4 p-4">{children}</main>
      </div>

      {/* Toaster Component */}
      <Toaster />
    </div>
  );
}
